name: Build Plugin

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Plugin version'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ vars.DEVPILOT_ENV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set Config
        run: |
          touch src/main/resources/config/local.properties
          echo "${{ vars.DEVPILOT_CONFIG }}" >> src/main/resources/config/local.properties

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v2
        with:
          name: plugin-artifact
          path: build/distributions/DevPilot-*.zip